# Generated by Django 4.1.5 on 2023-07-24 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_hackathons', to=settings.AUTH_USER_MODEL),
        ),
    ]
