# Generated by Django 4.1.5 on 2023-07-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kyc_document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
